### ISSUE TITLE
the .tsv file is lack of h-dimensional feature (food-101N)

### ISSUE THREAD

**Issue by ljmiao** [kuanghuei/clean-net#4]
in convert_data.py, the function convert_verified requires the format of the .tsv file should be [sample key, class name, verification label, h-dimensional feature delimited by ','] or
[sample key, image url, class name, verification label, h-dimensional feature delimited by ',']. But there is no h-dimensional feature in the file?

**Comment by kuanghuei** [comment]
Sorry for the confusion. h-dimension feature should be from the classification model you train. It is not included in the metadata we released.
