### ISSUE TITLE
convert data issue

### ISSUE THREAD

**Issue by yaojunyi721** [kuanghuei/clean-net#6]
Awesome work! 
When I try to convert data it says ValueError: not enough values to unpack (expected 4, got 2)
I'm using Food-101N dataset and your original py file.
Any hint or clue of why this would happen?

**Comment by House-Leo** [comment]
I have the same problem.
Can anyone fix it?

**Comment by kuanghuei** [comment]
I think this was asked in #4 . Please feel free to reopen this issue if it isn't the cause.

**Comment by House-Leo** [comment]
> I think this was asked in #4 . Please feel free to reopen this issue if it isn't the cause.

Thanks! I got it . Would you mind provide the .tsv you trained to me?

**Comment by kuanghuei** [comment]
I don't have it anymore unfortunately.
