### ISSUE TITLE
Confused about the reference data set?

### ISSUE THREAD

**Issue by rosefun** [kuanghuei/clean-net#7]
Q1: Is the reference set is labeled correctly by human?
Q2: We can sample a subset (also called reference set) to extract features as reference feature vector，but I don't find the discussion about the size of the subset? Is it an unimportant hypermeter?

**Comment by kuanghuei** [comment]
Q1: Yes
Q2: Depending on how much human supervision ($) you can afford. The more human supervision you add, the better performance that you can achieve.
